/**
 * Puts the demo deliverables into R2, using the manifest `seed-devflow.mjs` writes.
 *
 * The seed can only write rows; the bytes live in a bucket it has no credentials for.
 * Without this step every seeded file answers 410 ("no longer in storage") — which is
 * the download route being honest about a real inconsistency, and which in a demo
 * looks exactly like a broken feature.
 *
 * The three demo files are generated rather than committed: a PNG copied from the
 * favicon, a one-page PDF built here so its xref offsets are computed rather than
 * counted by hand, and a plain-text release form.
 *
 *   node scripts/db/seed-uploads.mjs             # uploads to the remote bucket
 *   node scripts/db/seed-uploads.mjs --local     # to wrangler's local storage instead
 *
 * Run it after the seed, against the same environment the seed wrote to.
 */
import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

const MANIFEST = new URL('./.seed-uploads.json', import.meta.url);
const BUCKET = 'untitledconference-uploads';
const REMOTE = !process.argv.includes('--local');

/** A one-page PDF that actually opens: offsets are accumulated, never hand-counted. */
function buildPdf(line) {
	const content = `BT /F1 16 Tf 72 700 Td (${line.replace(/[()\\]/g, '\\$&')}) Tj ET\n`;
	const objects = [
		'<< /Type /Catalog /Pages 2 0 R >>',
		'<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
		'<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] ' +
			'/Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
		'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
		`<< /Length ${content.length} >>\nstream\n${content}endstream`
	];

	let pdf = '%PDF-1.4\n';
	const offsets = [];
	for (const [i, body] of objects.entries()) {
		offsets.push(pdf.length);
		pdf += `${i + 1} 0 obj\n${body}\nendobj\n`;
	}

	const startxref = pdf.length;
	// Every xref entry is exactly 20 bytes, including the trailing space. A reader that
	// seeks by offset gets the wrong object if it is 19 or 21.
	pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
	for (const offset of offsets) pdf += `${String(offset).padStart(10, '0')} 00000 n \n`;
	pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${startxref}\n%%EOF\n`;

	return Buffer.from(pdf, 'latin1');
}

const RELEASE_FORM = `DEVFLOW CONF 2027 — SPEAKER RELEASE

I confirm that I hold the rights to the material in my session and grant DevFlow
Conf permission to record it and publish the recording.

Signed:  Priya Raman
Date:    12 March 2027

--
Demo data. This file was generated by scripts/db/seed-uploads.mjs.
`;

function sources() {
	const dir = mkdtempSync(join(tmpdir(), 'devflow-uploads-'));
	const png = join(dir, 'demo.png');
	const pdf = join(dir, 'demo.pdf');
	const txt = join(dir, 'demo.txt');

	writeFileSync(png, readFileSync(new URL('../../static/favicon.png', import.meta.url)));
	writeFileSync(pdf, buildPdf('DevFlow Conf 2027 — demo slide deck'));
	writeFileSync(txt, RELEASE_FORM);

	return { png, pdf, txt };
}

const manifest = JSON.parse(readFileSync(MANIFEST, 'utf8'));
if (manifest.length === 0) {
	console.error('Manifest is empty — run scripts/db/seed-devflow.mjs first.');
	process.exit(1);
}

const files = sources();
console.log(`Uploading ${manifest.length} objects to ${BUCKET} (${REMOTE ? 'remote' : 'local'}) …`);

for (const entry of manifest) {
	const file = files[entry.source];
	if (!file) {
		console.error(`No demo file for source "${entry.source}" — skipping ${entry.key}`);
		process.exitCode = 1;
		continue;
	}
	execFileSync(
		'npx',
		[
			'wrangler',
			'r2',
			'object',
			'put',
			`${BUCKET}/${entry.key}`,
			'--file',
			file,
			'--content-type',
			entry.contentType,
			REMOTE ? '--remote' : '--local'
		],
		{ stdio: 'inherit' }
	);
}

console.log('Done. Every seeded deliverable now has its bytes.');
