#!/bin/bash
# PreToolUse hook: protect sensitive files from edits.
#
# Blocks Write/Edit operations on files that should never be modified by agents:
# - Environment files (.env, .env.local)
# - Lock files (package-lock.json)
# - Credentials and keys (*.pem, *.key)
# - Git internals (.git/)

INPUT=$(cat)
FILE_PATH=$(echo "$INPUT" | jq -r '.tool_input.file_path // empty')

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

REASON=""

# Environment files
if [[ "$FILE_PATH" == *.env ]] || [[ "$FILE_PATH" == *.env.local ]] || [[ "$FILE_PATH" == */.env.* ]]; then
  REASON="Blocked: environment files contain secrets and must be edited manually"
fi

# Lock files
if [[ "$FILE_PATH" == *package-lock.json ]]; then
  REASON="Blocked: package-lock.json is auto-generated by npm install — do not edit directly"
fi

# Credential files
if [[ "$FILE_PATH" == *.pem ]] || [[ "$FILE_PATH" == *.key ]] || [[ "$FILE_PATH" == *credentials* ]]; then
  REASON="Blocked: credential/key files must not be modified by agents"
fi

# Git internals
if [[ "$FILE_PATH" == */.git/* ]]; then
  REASON="Blocked: .git/ internals must not be modified directly"
fi

if [ -n "$REASON" ]; then
  jq -n --arg reason "$REASON" '{
    hookSpecificOutput: {
      hookEventName: "PreToolUse",
      permissionDecision: "deny",
      permissionDecisionReason: $reason
    }
  }'
else
  exit 0
fi
