services:
  project-db:
    image: postgres
    container_name: postgres-vibe-starter
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: local
  test-db:
    image: postgres
    container_name: postgres-vibe-starter-test
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: test
